name: Sync Anthropic Release Notes

on:
  schedule:
    # Runs once every 24h at 00:15 UTC
    - cron: "15 0 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: sync-release-notes
  cancel-in-progress: false

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Download latest Markdown files
        run: |
          set -euo pipefail

          FOLDER="Official Claude Releases"
          mkdir -p "$FOLDER"

          # Source URL -> destination filename
          FILES=(
            "https://raw.githubusercontent.com/anthropics/claude-code/main/CHANGELOG.md|CHANGELOG.md"
            "https://docs.anthropic.com/en/release-notes/api.md|api.md"
            "https://docs.anthropic.com/en/release-notes/claude-apps.md|claude-apps.md"
            "https://docs.anthropic.com/en/release-notes/system-prompts.md|system-prompts.md"
            "https://docs.anthropic.com/en/release-notes/claude-code.md|claude-code.md"
          )

          # Fetch each file and only overwrite if the content changed
          for entry in "${FILES[@]}"; do
            IFS="|" read -r URL NAME <<< "$entry"
            TMP="$FOLDER/$NAME.tmp"
            OUT="$FOLDER/$NAME"

            echo "Fetching $URL -> $OUT"
            curl -fsSL -H "Accept: text/markdown, text/plain;q=0.9, text/x-markdown;q=0.9, */*;q=0.1" "$URL" -o "$TMP"

            # If file exists and is identical, keep existing; otherwise replace
            if [[ -f "$OUT" ]] && cmp -s "$TMP" "$OUT"; then
              echo "No changes for $NAME"
              rm -f "$TMP"
            else
              mv -f "$TMP" "$OUT"
              echo "Updated $OUT"
            fi
          done

      - name: Commit and push if changes
        run: |
          set -euo pipefail

          if ! git diff --quiet -- "Official Claude Releases/"; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add "Official Claude Releases/"
            git commit -m "chore: sync Anthropic release notes ($(date -u +%F))"
            git push
            echo "Changes pushed."
          else
            echo "No updates to commit."
          fi
