name: Sync Anthropic Release Notes

on:
  schedule:
    - cron: "15 0 * * *"   # daily at 00:15 UTC
  workflow_dispatch: {}
  push:
    paths:
      - ".github/workflows/sync-release-notes.yml"

permissions:
  contents: write

concurrency:
  group: sync-release-notes
  cancel-in-progress: false

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Download latest Markdown files and stage real changes
        id: sync_files
        shell: bash
        run: |
          set -euo pipefail

          FOLDER="Official Claude Releases"
          mkdir -p "$FOLDER"

          FILES=(
            "https://raw.githubusercontent.com/anthropics/claude-code/main/CHANGELOG.md|CHANGELOG.md"
            "https://docs.anthropic.com/en/release-notes/api.md|api.md"
            "https://docs.anthropic.com/en/release-notes/claude-apps.md|claude-apps.md"
            "https://docs.anthropic.com/en/release-notes/system-prompts.md|system-prompts.md"
            "https://docs.anthropic.com/en/release-notes/claude-code.md|claude-code.md"
          )

          CHANGED_FILES=()
          COMMIT_BODY=""
          README_LIST=""

          for entry in "${FILES[@]}"; do
            IFS="|" read -r URL NAME <<< "$entry"
            OUT="$FOLDER/$NAME"
            TMP="$OUT.tmp"

            echo "Fetching $URL -> $OUT"
            curl -fsSL -H "Accept: text/markdown, text/plain;q=0.9, text/x-markdown;q=0.9, */*;q=0.1" "$URL" -o "$TMP"

            # Skip if identical ignoring whitespace
            if [[ -f "$OUT" ]] && diff --no-index -w "$OUT" "$TMP" >/dev/null 2>&1; then
              echo "No substantive changes for $NAME"
              rm -f "$TMP"
              continue
            fi

            # Diffstat BEFORE overwrite
            NUMSTAT=$(diff --no-index --numstat "${OUT:-/dev/null}" "$TMP" 2>/dev/null || true)
            ADDED=$(echo "$NUMSTAT" | awk '{print $1}')
            DELETED=$(echo "$NUMSTAT" | awk '{print $2}')

            # Highlights: first few added headings/bullets (fallback to first lines)
            HILITES=$(
              diff -u --new-file "${OUT:-/dev/null}" "$TMP" \
                | sed -n 's/^+[^+].*/\0/p' \
                | sed 's/^+//' \
                | grep -E '^(#|##|###|- |\* )' \
                | head -n 6 || true
            )
            if [[ -z "$HILITES" ]]; then
              HILITES=$(
                diff -u --new-file "${OUT:-/dev/null}" "$TMP" \
                  | sed -n 's/^+[^+].*/\0/p' \
                  | sed 's/^+//' \
                  | head -n 3 || true
              )
            fi

            mv -f "$TMP" "$OUT"
            CHANGED_FILES+=("$OUT")

            # Commit body details
            COMMIT_BODY+=$'- '"$NAME"' (+'"${ADDED:-0}"' / -'"${DELETED:-0}"')\n'
            if [[ -n "$HILITES" ]]; then
              while IFS= read -r line; do
                COMMIT_BODY+="    • ${line}\n"
              done <<< "$HILITES"
            fi

            # README summary line
            README_LIST+="- ${NAME} (+${ADDED:-0} / -${DELETED:-0})"$'\n'
          done

          # Stage only actually changed files
          if [[ ${#CHANGED_FILES[@]} -gt 0 ]]; then
            git add "${CHANGED_FILES[@]}"
          fi

          # Persist data for later steps
          printf '%b' "$COMMIT_BODY" > /tmp/commit_body.txt
          printf '%b' "$README_LIST" > /tmp/readme_list.txt

      - name: Update status in 'Official Claude Releases/README.md' (always)
        shell: bash
        run: |
          set -euo pipefail

          FOLDER="Official Claude Releases"
          README="$FOLDER/README.md"

          # Timestamps
          DATE_UTC="$(date -u +'%Y-%m-%d %H:%M %Z')"
          DATE_OSLO="$(TZ=Europe/Oslo date +'%Y-%m-%d %H:%M %Z')"

          # Per-run summary (may be empty)
          README_LIST="$(cat /tmp/readme_list.txt 2>/dev/null || true)"

          STATUS_START="<!-- sync-status:start -->"
          STATUS_END="<!-- sync-status:end -->"

          # Build the status block file
          {
            echo "$STATUS_START"
            echo ""
            echo "### 🔄 Last sync"
            echo "- UTC: \`$DATE_UTC\`"
            echo "- Europe/Oslo: \`$DATE_OSLO\`"
            echo ""
            if [[ -n "$README_LIST" ]]; then
              echo "### ✅ Files updated this run"
              echo ""
              echo "$README_LIST"
            else
              echo "### ℹ️ No content changes in tracked files this run"
              echo ""
            fi
            echo "$STATUS_END"
          } > /tmp/status_block.md

          # Ensure README exists inside the folder
          if [[ ! -f "$README" ]]; then
            mkdir -p "$FOLDER"
            cat > "$README" <<'EOF'
# Official Claude Releases

This folder mirrors selected Anthropic release notes for easy tracking.  
The status section below is updated by a daily GitHub Action.

EOF
          fi

          # Replace (or append) the status block using a tiny Python script to avoid quoting issues
          python3 - <<'PY'
import re, pathlib
readme = pathlib.Path("Official Claude Releases/README.md")
status = pathlib.Path("/tmp/status_block.md").read_text(encoding="utf-8")
if readme.exists():
    text = readme.read_text(encoding="utf-8")
else:
    text = "# Official Claude Releases\n\n"
start = "<!-- sync-status:start -->"
end = "<!-- sync-status:end -->"
if start in text and end in text:
    new = re.sub(r'<!-- sync-status:start -->.*?<!-- sync-status:end -->', status, text, flags=re.S)
else:
    new = text.rstrip() + "\n\n---\n\n" + status + "\n"
readme.write_text(new, encoding="utf-8")
PY

          # Always stage this README so there is a visible run marker
          git add "$README"

      - name: Commit and push
        shell: bash
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          TITLE="chore: daily sync Anthropic release notes ($(date -u +%F))"
          BODY=$(cat /tmp/commit_body.txt 2>/dev/null || true)

          # Determine if anything besides the README changed
          FOLDER="Official Claude Releases"
          README_PATH="$FOLDER/README.md"
          if git diff --cached --name-only | grep -F -v -- "$README_PATH" | grep -q .; then
            git commit -m "$TITLE" -m "$BODY"
          else
            git commit -m "$TITLE" -m "No release-note content changes; updated status in '$README_PATH'."
          fi

          git push
